#!/bin/sh
### BEGIN INIT INFO
# Provides:
# Short-Description: Start NFS Mount
# Description:       Mount NFS as target of record
### END INIT INFO

. /opt/wz_mini/wz_mini.conf

case "$1" in
start)
	echo "#####$(basename "$0")#####"

	if [[ "$ENABLE_NFSv4" == "true" ]]; then
		# Apply the patch. The script here is idempotent.
		if /opt/wz_mini/bin/bash -c "/opt/wz_mini/usr/bin/nfs.sh start"; then
			echo "NFS mount started successfully."
			exit 0
		else
			# If the patch failed, ensure the iCamera shim script calls the stock version (Eg. in the event of a system upgrade to an unsupported version)
			echo "NFS mount failed."
		fi
	fi
	;;
stop)
	/opt/wz_mini/bin/bash -c "/opt/wz_mini/usr/bin/nfs.sh stop"
	echo "NFS mount stopped successfully."
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
